/**
 * Quiz U - Network Protocol Definitions & Message Types
 */

const MSG_TYPES = {
    // Host -> Server
    HOST_CREATE_ROOM: 'HOST_CREATE_ROOM',
    HOST_SET_PACK: 'HOST_SET_PACK',
    HOST_START_GAME: 'HOST_START_GAME',
    HOST_SELECT_QUESTION: 'HOST_SELECT_QUESTION',
    HOST_ACTIVATE_BUZZER: 'HOST_ACTIVATE_BUZZER',
    HOST_JUDGE_ANSWER: 'HOST_JUDGE_ANSWER',
    HOST_SHOW_ANSWER: 'HOST_SHOW_ANSWER',
    HOST_TOGGLE_PAUSE: 'HOST_TOGGLE_PAUSE',
    HOST_CLOSE_QUESTION: 'HOST_CLOSE_QUESTION',
    HOST_PASS_QUESTION: 'HOST_PASS_QUESTION',
    HOST_UPDATE_SCORE: 'HOST_UPDATE_SCORE',
    HOST_KICK_PLAYER: 'HOST_KICK_PLAYER',
    HOST_NEXT_ROUND: 'HOST_NEXT_ROUND',
    HOST_SET_LOCAL_HOST: 'HOST_SET_LOCAL_HOST',
    HOST_UPDATE_ROOM_SETTINGS: 'HOST_UPDATE_ROOM_SETTINGS',
    HOST_SET_CAT_TARGET: 'HOST_SET_CAT_TARGET',
    HOST_SET_AUCTION_LEADER: 'HOST_SET_AUCTION_LEADER',
    HOST_SET_AUCTION_BETS: 'HOST_SET_AUCTION_BETS',
    HOST_START_AUCTION_ANSWER: 'HOST_START_AUCTION_ANSWER',

    // Player -> Server
    PLAYER_JOIN: 'PLAYER_JOIN',
    PLAYER_BUZZ: 'PLAYER_BUZZ',
    PLAYER_SUBMIT_ANSWER: 'PLAYER_SUBMIT_ANSWER',
    PLAYER_AUCTION_BET: 'PLAYER_AUCTION_BET',
    PLAYER_CAT_TRANSFER: 'PLAYER_CAT_TRANSFER',

    // Server -> Client(s)
    ROOM_CREATED: 'ROOM_CREATED',
    PLAYER_JOINED: 'PLAYER_JOINED',
    PLAYER_LEFT: 'PLAYER_LEFT',
    ROOM_STATE: 'ROOM_STATE',
    ROOM_SETTINGS_UPDATED: 'ROOM_SETTINGS_UPDATED',
    QUESTION_ACTIVE: 'QUESTION_ACTIVE',
    BUZZER_READY: 'BUZZER_READY',
    BUZZ_LOCKED: 'BUZZ_LOCKED',
    BUZZ_RESET: 'BUZZ_RESET',
    ANSWER_SUBMITTED: 'ANSWER_SUBMITTED',
    AUCTION_BET_MADE: 'AUCTION_BET_MADE',
    AUCTION_ANSWER_START: 'AUCTION_ANSWER_START',
    CAT_TRANSFERRED: 'CAT_TRANSFERRED',
    ANSWER_TIMEOUT: 'ANSWER_TIMEOUT',
    ROUND_CHANGED: 'ROUND_CHANGED',
    GAME_FINISHED: 'GAME_FINISHED',
    SCORE_UPDATED: 'SCORE_UPDATED',
    JUDGE_RESULT: 'JUDGE_RESULT',
    GAME_PAUSED: 'GAME_PAUSED',
    SHOW_ANSWER: 'SHOW_ANSWER',
    QUESTION_CLOSED: 'QUESTION_CLOSED',
    ERROR: 'ERROR',

    // System
    PING: 'PING',
    PONG: 'PONG'
};

const ERROR_CODES = {
    ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
    ROOM_FULL: 'ROOM_FULL',
    GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
    NAME_ALREADY_TAKEN: 'NAME_ALREADY_TAKEN',
    HOST_ALREADY_EXISTS: 'HOST_ALREADY_EXISTS',
    HOST_REQUIRED: 'HOST_REQUIRED',
    NOT_ENOUGH_PLAYERS: 'NOT_ENOUGH_PLAYERS',
    INVALID_ACTION: 'INVALID_ACTION',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    INVALID_PAYLOAD: 'INVALID_PAYLOAD'
};

function createMessage(type, payload = {}) {
    return JSON.stringify({
        type,
        payload,
        timestamp: Date.now()
    });
}

function parseMessage(rawMessage) {
    try {
        const parsed = JSON.parse(rawMessage);
        if (!parsed || typeof parsed !== 'object' || typeof parsed.type !== 'string') {
            return null;
        }
        return parsed;
    } catch {
        return null;
    }
}

module.exports = {
    MSG_TYPES,
    ERROR_CODES,
    createMessage,
    parseMessage
};
